[metadata]
name = 'bidscoin'
version = '3.7.0-dev'
description = 'Map source-level neuroimaging data onto a BIDS data structure'
author = 'Marcel Zwiers'
author_email = 'm.zwiers@donders.ru.nl'
license = 'GPL3'
url = 'https://github.com/Donders-Institute/bidscoin'

[requires]
python_version = ['3.8', '3.9']

[build-system]
requires = ['setuptools', 'wheel']
